### ISSUE TITLE
Typo in Bitparsers Slide in Meow

### ISSUE THREAD

**Issue by MohammadOST** [SirSaleh/Portfolio#1]
A simple effect generated by Light-blender (our light-mapping product) and **Mewuser's** reaction to
Should be
A simple effect generated by Light-blender (our light-mapping product) and **Meowuser's** reaction to

![Bug](https://github.com/SirSaleh/Portfolio/assets/68914853/917c93d0-0e2c-4847-8d77-998418bb9ce4)

**Comment by SirSaleh** [comment]
OOOooOOOps, Thank you for discovering this **lethal** issue =)))
We will investigate ASAP.
